name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 这里指的是你想要发布的分支，通常为 main 或 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有写权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 使用你项目所需的 Node.js 版本

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build  # 使用你的打包命令，默认是 `npm run build`

      - name: 上传dist
        run: |
          echo ::group::Archive dist directory
          tar -czvf dist.tar.gz dist  # 将 dist 目录打包为 dist.tar.gz
          echo ::endgroup::

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4  # 上传打包好的 dist 目录
        with:
          name: dist-artifact
          path: dist.tar.gz  # 上传打包文件
          retention-days: 1  # 工件保留 1 天

      # 创建新的 tag（例如基于时间或其他命名规则）
      - name: Create tag
        id: tag_step
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # 根据当前时间生成 tag
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # 将 tag 名称存储到环境变量

      - name: Create GitHub Release
        id: create_release  # 设置步骤 ID 以便后续引用
        uses: actions/create-release@v1  # 创建 GitHub Release
        with:
          tag_name: ${{ env.TAG_NAME }}  # 使用当前 commit 的 SHA 作为 tag 名称
          release_name: "Release ${{ env.TAG_NAME }}"  # 设置发布名称
          body: "This is an automated release containing the latest build."  # 发布描述
          draft: false  # 设为 false 表示创建正式发布
          prerelease: false  # 设为 false 表示这不是预发布
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 需要 GitHub 提供的 token 用于身份验证

      - name: Upload dist to Release
        uses: actions/upload-release-asset@v1  # 上传打包文件到 GitHub Release
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # 获取上一步创建发布的上传 URL
          asset_path: dist.tar.gz  # 上传的文件路径
          asset_name: dist.tar.gz  # 文件在 Release 中显示的名称
          asset_content_type: application/gzip  # 文件类型
